# These variables are defined in workspace.code-workspace
# Update according to your setup
# Then, choose an REST Client Environment (Ctrl+Alt+E)
# @endpoint (Base URL of your organization) = http://localhost:3000
# @token (Auth token) = YWRtaW46Ym9vdHN0cmFwOmFkbWluMTIz
# @ds_host (hostname:port of Pg DataSource) = localhost:5432
# @ds_user (Pg user) = demouser
# @dh_pass (Pg password) = demopass

### Create Postgres connection
# @name createDataSource
POST {{endpoint}}/api/entities/dataSources/
Content-Type: application/vnd.gooddata.api+json
Authorization: Bearer {{token}}

<@ ./db.json

### GET Postgres connection
# @name getDataSource
GET {{endpoint}}/api/entities/dataSources/covid.cz
Content-Type: application/vnd.gooddata.api+json
Authorization: Bearer {{token}}

### Create workspace
# @name createWorkspace
POST {{endpoint}}/api/entities/workspaces/
Content-Type: application/vnd.gooddata.api+json
Authorization: Bearer {{token}}

< ./workspace.json

### GET workspace
# @name getWorkspace
GET {{endpoint}}/api/entities/workspaces/covid.cz
Content-Type: application/vnd.gooddata.api+json
Authorization: Bearer {{token}}

### Get Physical Model
# @name getPhysicalModel
GET {{endpoint}}/api/layout/dataSources/covid.cz/physicalModel
Content-Type: application/json
Authorization: Bearer {{token}}

### Store Physical Model
# @name storePhysicalModel
PUT {{endpoint}}/api/layout/dataSources/covid.cz/physicalModel
Content-Type: application/json
Authorization: Bearer {{token}}

< ./pdm.json

### Get semantic model
# @name getSemanticModel
GET {{endpoint}}/api/layout/workspaces/covid.cz/logicalModel/
Content-Type: application/json
Authorization: Bearer {{token}}

### Publish semantic model
# @name publishSemanticModel
PUT {{endpoint}}/api/layout/workspaces/covid.cz/logicalModel/
Content-Type: application/json
Authorization: Bearer {{token}}

< ./ldm.json

### Get analytics model objects
# @name getAnalyticsModelObjects
GET {{endpoint}}/api/layout/workspaces/covid.cz/analyticsModel/
Content-Type: application/json
Authorization: Bearer {{token}}

### Create analytics model objects
# @name createAnalyticsModelObjects
PUT {{endpoint}}/api/layout/workspaces/covid.cz/analyticsModel/
Content-Type: application/json
Authorization: Bearer {{token}}

< ./analytics_model.json

### Get measures
# @name getMeasures
GET {{endpoint}}/api/entities/workspaces/covid.cz/metrics/
Content-Type: application/json
Authorization: Bearer {{token}}

### Create metrics
# @name createMetrics
POST {{endpoint}}/api/entities/workspaces/covid.cz/metrics/
Content-Type: application/vnd.gooddata.api+json
Authorization: Bearer {{token}}

< ./metrics.json
